name: Build & Test

on:
  push:
    branches-ignore: ['example']
    paths-ignore: ['README.md']
  pull_request:
    branches-ignore: [ 'example' ]
    paths-ignore: [ 'README.md' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...